# Generated by Django 5.0 on 2025-12-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('consumable', 'Consumable'), ('artifact', 'Artifact'), ('misc', 'Misc')], max_length=20)),
                ('price', models.IntegerField()),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('blood_bonus', models.IntegerField(default=0)),
                ('is_usable', models.BooleanField(default=False)),
            ],
        ),
    ]
