# Generated by Django 5.0 on 2026-01-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_gempack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='item_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.gempack'),
            preserve_default=False,
        ),
    ]
